development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("redis://h:p52653741f14fa3cd16b7f3c08a9a10b76a147279a8c2cdd74a5c560139747dcb@ec2-35-172-5-233.compute-1.amazonaws.com:12479") %>
  channel_prefix: instafood_production
